#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/stainless-sdks/strezless-musick-nexus-metadata-go"

echo "==> Building strezless-musick-nexus-metadata"
go build ./cmd/strezless-musick-nexus-metadata
